### ISSUE TITLE
Reboot Magic 2 LAN 1-1 does not work

### ISSUE THREAD

**Issue by mrhell69** [2Fake/devolo_plc_api#121]
**Describe the bug**
I have a reboot routine running at 4:30 AM.

What it does:
reboot fritzbox 7590
reboot Magic 2 LAN 1-1
reboot Magic 2 devolo-1
reboot Magic 2 devolo-2
reboot Magic 2 devolo-wifi

All devices reboot correctly (Webinterface is showing timestmap within less than 5 minutes).
Except Magic 2 LAN 1-1 (that has an old timestamp --> more hours).

**Used device**
Magic 2 LAN 1-1 (7.12.6.131 (2022-11-17))

**To Reproduce**
1. Putting output of my script here:

```
root@raspberrypi:/home/root/devolo# ./all_restart
<?xml version="1.0"?>
<s:Envelope xmlns:s="http://schemas.xmlsoap.org/soap/envelope/" s:encodingStyle="http://schemas.xmlsoap.org/soap/encoding/">
<s:Body>
<u:RebootResponse xmlns:u="urn:dslforum-org:service:DeviceConfig:1"></u:RebootResponse>
</s:Body>
</s:Envelope>Internet is back
rebooting devolo-lan
devolo-lan is back for reboot
rebooting devolo-lan
Traceback (most recent call last):
  File "/home/root/devolo/devolo-lan.py", line 19, in <module>
    run()
  File "/home/root/devolo/devolo-lan.py", line 12, in run
    with Device(ip=IP) as dpa:
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 80, in __enter__
    self.connect()
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 137, in connect
    asyncio.run(self.async_connect())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 132, in async_connect
    raise DeviceNotFound(self.ip)
devolo_plc_api.exceptions.device.DeviceNotFound: The device 192.168.178.22 did not answer.
devolo-2 is back for reboot
rebooting devolo-2
success
Traceback (most recent call last):
  File "/home/root/devolo/devolo-2.py", line 19, in <module>
    run()
  File "/home/root/devolo/devolo-2.py", line 17, in run
    print("success" if dpa.device.restart() else "failed")
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 85, in __exit__
    self.disconnect()
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 152, in disconnect
    asyncio.run(self.async_disconnect())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 145, in async_disconnect
    await self._zeroconf.async_close()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/asyncio.py", line 233, in async_close
    await self.zeroconf._async_close()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 991, in _async_close
    await self.engine._async_close()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 218, in _async_close
    self._async_shutdown()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 228, in _async_shutdown
    wrapped_transport.transport.close()
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 700, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Please disconnect properly from the device.
devolo-1 is back for reboot
rebooting devolo-1
success
Traceback (most recent call last):
  File "/home/root/devolo/devolo-1.py", line 19, in <module>
    run()
  File "/home/root/devolo/devolo-1.py", line 17, in run
    print("success" if dpa.device.restart() else "failed")
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 85, in __exit__
    self.disconnect()
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 152, in disconnect
    asyncio.run(self.async_disconnect())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 145, in async_disconnect
    await self._zeroconf.async_close()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/asyncio.py", line 233, in async_close
    await self.zeroconf._async_close()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 991, in _async_close
    await self.engine._async_close()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 218, in _async_close
    self._async_shutdown()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 228, in _async_shutdown
    wrapped_transport.transport.close()
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 700, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Please disconnect properly from the device.
devolo-wifi is back for reboot
rebooting devolo-wifi
success
Traceback (most recent call last):
  File "/home/root/devolo/devolo-wifi.py", line 19, in <module>
    run()
  File "/home/root/devolo/devolo-wifi.py", line 17, in run
    print("success" if dpa.device.restart() else "failed")
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 85, in __exit__
    self.disconnect()
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 152, in disconnect
    asyncio.run(self.async_disconnect())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/dist-packages/devolo_plc_api/device.py", line 145, in async_disconnect
    await self._zeroconf.async_close()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/asyncio.py", line 233, in async_close
    await self.zeroconf._async_close()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 991, in _async_close
    await self.engine._async_close()  # pylint: disable=protected-access
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 218, in _async_close
    self._async_shutdown()
  File "/usr/local/lib/python3.9/dist-packages/zeroconf/_core.py", line 228, in _async_shutdown
    wrapped_transport.transport.close()
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 700, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 746, in call_soon
    self._check_closed()
  File "/usr/lib/python3.9/asyncio/base_events.py", line 510, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Please disconnect properly from the device.
reboot done
```

**Expected behavior**
After rebooting devolo-##### I would like to see also success for  Magic 2 LAN 1-1.
All others are showing in the first line success.

**Additional context**
none

**Comment by mrhell69** [comment]
Adding script here:

root@raspberrypi:/home/root/devolo# cat all_restart 
#!/bin/bash

ipAddress="192.168.178.1"
username="admin"
password="secret"

xdebug=on

curl -k -m 5 --anyauth -u "$username:$password" http://$ipAddress:49000/upnp/control/deviceconfig -H 'Content-Type: text/xml; charset="utf-8"' -H "SoapAction:urn:dslforum-org:service:DeviceConfig:1#Reboot" -d "<?xml version='1.0' encoding='utf-8'?><s:Envelope s:encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' xmlns:s='http://schemas.xmlsoap.org/soap/envelope/'><s:Body><u:Reboot xmlns:u='urn:dslforum-org:service:DeviceConfig:1'/></s:Body></s:Envelope>"

# wait until fritzbox restarting
sleep 10
# waiting for internet back
while ! $(ping -c 1 www.oracle.com > /dev/null 2>&1); do sleep 3; done
if [ "$xdebug" = "on" ]; then echo Internet is back; fi
if [ "$xdebug" = "on" ]; then echo rebooting devolo-lan; fi

# check devolo-lan is available 
while ! $(ping -c 1 192.168.178.22  > /dev/null 2>&1); do sleep 3; done
if [ "$xdebug" = "on" ]; then echo devolo-lan is back for reboot; fi
# reboot devolo-lan
if [ "$xdebug" = "on" ]; then echo rebooting devolo-lan; fi
python devolo-lan.py

# check devolo-2 is available 
while ! $(ping -c 1 192.168.178.23 > /dev/null 2>&1); do sleep 3; done
if [ "$xdebug" = "on" ]; then echo devolo-2 is back for reboot; fi
# reboot devolo-2
if [ "$xdebug" = "on" ]; then echo rebooting devolo-2; fi
python devolo-2.py

# check devolo-1 is available 
while ! $(ping -c 1 192.168.178.42 > /dev/null 2>&1); do sleep 3; done
if [ "$xdebug" = "on" ]; then echo devolo-1 is back for reboot; fi
# reboot devolo-1
if [ "$xdebug" = "on" ]; then echo rebooting devolo-1; fi
python devolo-1.py

# check devolo-wifi is available 
while ! $(ping -c 1 192.168.178.20 > /dev/null 2>&1); do sleep 3; done
if [ "$xdebug" = "on" ]; then echo devolo-wifi is back for reboot; fi
# reboot devolo-wifi
if [ "$xdebug" = "on" ]; then echo rebooting devolo-wifi; fi
python  devolo-wifi.py

if [ "$xdebug" = "on" ]; then echo reboot done; fi

exit
---------------------------------------------------------------------
root@raspberrypi:/home/root/devolo# cat devolo-lan.py 
from devolo_plc_api import Device

# IP of the device to query
IP = "192.168.178.22"

# Password, if the device has one. It is the same as the Web-UI has. It no password is set, you can remove the password
# parameter or set it to None.
PASSWORD = "secret"


def run():
    with Device(ip=IP) as dpa:
        # Set the password
        dpa.password = PASSWORD

        # Restart the device. If the restart will happen shortly, True is returned, otherwise False.
        print("success" if dpa.device.restart() else "failed")
if __name__ == "__main__":
    run()
---------------------------------------------------------------------
root@raspberrypi:/home/root/devolo# cat devolo-2.py 
from devolo_plc_api import Device

# IP of the device to query
IP = "192.168.178.23"

# Password, if the device has one. It is the same as the Web-UI has. It no password is set, you can remove the password
# parameter or set it to None.
PASSWORD = "secret"


def run():
    with Device(ip=IP) as dpa:
        # Set the password
        dpa.password = PASSWORD

        # Restart the device. If the restart will happen shortly, True is returned, otherwise False.
        print("success" if dpa.device.restart() else "failed")
if __name__ == "__main__":
    run()
---------------------------------------------------------------------
root@raspberrypi:/home/root/devolo# cat devolo-1.py 
from devolo_plc_api import Device

# IP of the device to query
IP = "192.168.178.42"

# Password, if the device has one. It is the same as the Web-UI has. It no password is set, you can remove the password
# parameter or set it to None.
PASSWORD = "secret"


def run():
    with Device(ip=IP) as dpa:
        # Set the password
        dpa.password = PASSWORD

        # Restart the device. If the restart will happen shortly, True is returned, otherwise False.
        print("success" if dpa.device.restart() else "failed")
if __name__ == "__main__":
    run()
---------------------------------------------------------------------
root@raspberrypi:/home/root/devolo# cat devolo-wifi.py 
from devolo_plc_api import Device

# IP of the device to query
IP = "192.168.178.20"

# Password, if the device has one. It is the same as the Web-UI has. It no password is set, you can remove the password
# parameter or set it to None.
PASSWORD = "secret"


def run():
    with Device(ip=IP) as dpa:
        # Set the password
        dpa.password = PASSWORD

        # Restart the device. If the restart will happen shortly, True is returned, otherwise False.
        print("success" if dpa.device.restart() else "failed")
if __name__ == "__main__":
    run()
---------------------------------------------------------------------

**Comment by Shutgun** [comment]
Hi @mrhell69 ,

we could have multiple reasons here. Is it always the same device that is failing? If so: is that device usable via the App? Did you try restart the device manually e.g. via the WebUI and does the issue persist afterwards?

I fixed the event loop issue locally and will push it soon, but that seems to be unrelated to your issue.

**Comment by mrhell69** [comment]
Hello @Shutgun,

I think I could solve the problem giving some more sleep between.
Sorry making trouble before checking more.
Maybe this can be an error of loosing vnc terminal disconnect.
So I started with screen -d -e all_restart 

Thx

You guys did a good job with this framework ;-)
