### ISSUE TITLE
warning when connecting to the first discovered device

### ISSUE THREAD

**Issue by ktn001** [2Fake/devolo_plc_api#127]
**Describe the bug**
In sync mode, the connection to the first discovered Devolo device give the following warning:

```
[2023-04-29 11:36_01[WARNING][_logger]: Error with socket 5 (('127.0.0.1', 5353))): [Errno 22] Invalid argument
Traceback (most recent call last):
  File "/usr/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
    self._sock.sendto(data, addr)
OSError: [Errno 22] Invalid argument
```

**Used device**
2 "Devolo Magic 2 LAN",   serial: `21....0601`, `21....0712`
1 "Devolo Magic 1 LAN",   serial: `20....0099`
2 "Devolo Magic 2 WiFi 6"   serial: `21....4309`, `21....4179`

**To Reproduce**
1. Create the following script

   ```
   #!/usr/bin/python3

   import logging

   import devolo_plc_api
   import devolo_plc_api.network
   from devolo_plc_api import Device

   FORMAT = '[%(asctime)s[%(levelname)s][%(module)s]: %(message)s'
   logging.basicConfig(level=logging.INFO, format=FORMAT, datefmt="%Y-%m-%d %H:%M_%S")

   devices = devolo_plc_api.network.discover_network()
   for serial in devices:
       print (f"before connect to {serial}")
       devices[serial].connect()
       print ("after connect")
   ```

1. run the script twice
   ```
   $ ./devolo.py 
   before connect to 21....0601
   [2023-04-29 11:53_02[WARNING][_logger]: Error with socket 4 (('127.0.0.1', 5353))): [Errno 22] Invalid argument
   Traceback (most recent call last):
     File "/usr/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
       self._sock.sendto(data, addr)
   OSError: [Errno 22] Invalid argument
   after connect
   before connect to 20....0099
   after connect
   before connect to 21....0712
   after connect
   before connect to 21....4179
   after connect
   before connect to 21....4309
   after connect
   $
   ```
   ```
    $ ./devolo.py 
   before connect to 20....0099
   [2023-04-29 11:53_32[WARNING][_logger]: Error with socket 4 (('127.0.0.1', 5353))): [Errno 22] Invalid argument
   Traceback (most recent call last):
     File "/usr/lib/python3.9/asyncio/selector_events.py", line 1056, in sendto
       self._sock.sendto(data, addr)
   OSError: [Errno 22] Invalid argument
   after connect
   before connect to 21....0712
   after connect
   before connect to 21....0601
   after connect
   before connect to 21....4309
   after connect
   before connect to 21....4179
   after connect
   ```

The warning appears for the first connection regardless of the device

**Expected behavior**
I would like to avoid this warning 

**Additional context**
Python version is 3.9.2

Installed modules:
```
$ pip3 list
Package             Version
------------------- --------------
anyio               3.6.2
async-timeout       4.0.2
certifi             2020.6.20
chardet             4.0.0
cupshelpers         1.0
dbus-python         1.2.16
devolo-plc-api      1.3.0
distro-info         1.0
fail2ban            0.11.2
gpg                 1.14.0-unknown
h11                 0.14.0
httpcore            0.17.0
httpx               0.24.0
idna                2.10
ifaddr              0.2.0
importlib-metadata  6.6.0
iotop               0.6
pip                 20.3.4
protobuf            4.22.3
pycairo             1.16.2
pycups              2.0.1
pycurl              7.43.0.6
PyGObject           3.38.0
pyinotify           0.9.6
pysmbc              1.0.23
python-apt          2.2.1
requests            2.25.1
setuptools          52.0.0
six                 1.16.0
sniffio             1.3.0
systemd-python      234
unattended-upgrades 0.1
urllib3             1.26.5
wheel               0.34.2
zeroconf            0.58.2
zipp                3.15.0
```

**Comment by Shutgun** [comment]
Hi @ktn001 , that is caused by the zeroconf dependency we use. By default it tries to scan on all interfaces including the loop back interface. If I limit scanning to a specific interface, the warning is gone.

I will try to take it upstream and I if they reject seeing this as a bug I will add code to exclude the loop back interface by default.
